-- SQL Script untuk setup database Mercure System di Supabase
-- Copy dan paste script ini di "SQL Editor" pada Dashboard Supabase Anda.

-- 1. Tabel Mitra (Partners)
CREATE TABLE IF NOT EXISTS partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- Nama umum (misal: Starbucks)
    image_url TEXT,
    name_id TEXT, desc_id TEXT, -- Bahasa Indonesia
    name_en TEXT, desc_en TEXT, -- Bahasa Inggris
    name_cn TEXT, desc_cn TEXT, -- Bahasa Mandarin
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabel Wisata (Attractions)
CREATE TABLE IF NOT EXISTS attractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT,
    map_url TEXT,
    title_id TEXT, desc_id TEXT,
    title_en TEXT, desc_en TEXT,
    title_cn TEXT, desc_cn TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Tabel Promo Hotel (Hotel Promos)
CREATE TABLE IF NOT EXISTS hotel_promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT,
    title_id TEXT, desc_id TEXT,
    title_en TEXT, desc_en TEXT,
    title_cn TEXT, desc_cn TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Tabel Event (Events)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT,
    title_id TEXT, desc_id TEXT,
    title_en TEXT, desc_en TEXT,
    title_cn TEXT, desc_cn TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Tabel Klaim Voucher (Voucher Claims)
CREATE TABLE IF NOT EXISTS voucher_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    user_name TEXT,
    mitra TEXT,
    promo TEXT,
    resi TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- CONTOH DATA AWAL (OPTIONAL - Boleh dihapus jika ingin input manual)
-- Insert 1 Mitra Contoh
INSERT INTO partners (name, image_url, name_id, desc_id, name_en, desc_en, name_cn, desc_cn)
VALUES (
    'Mie Gacoan Supratman', 
    'https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600',
    'Mie Gacoan Supratman', 'Diskon 10% All Menu',
    'Mie Gacoan Supratman', '10% Off All Menu',
    'Mie Gacoan Supratman', '全场 9 折'
);

-- Insert 1 Wisata Contoh
INSERT INTO attractions (image_url, map_url, title_id, desc_id, title_en, desc_en, title_cn, desc_cn)
VALUES (
    'https://images.unsplash.com/photo-1626244665487-19409848f066?w=800',
    'https://www.google.com/maps/dir/?api=1&origin=Mercure+Bandung+Nexa+Supratman&destination=Gedung+Sate+Bandung',
    'Gedung Sate', 'Ikon sejarah Kota Bandung dengan arsitektur klasik.',
    'Gedung Sate', 'Historical icon of Bandung with classic architecture.',
    '沙爹大厦 (Gedung Sate)', '具有古典建筑风格的万隆历史地标。'
);
